groups:
  - name: celestia-node
    rules:
    - alert: celestia_node_service_not_running
      expr: node_systemd_unit_state{name=~"celestia-(bridge|light|full).*", state="active"} == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Celestia Node service is not running (instance {{ $labels.instance }})"
        description: "Celestia Node service is not running\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: celestia_node_stop_syncing
      expr: delta(celestia_total_synced_headers[5m]) == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "celestia node {{ $labels.instance }} is stuck"
        description: "celestia node {{ $labels.instance }} is stuck"